import assert from "node:assert/strict";
import { AutomatonPlayer } from "../web/automaton.js";
let requests = [];
const player = new AutomatonPlayer(() => new Promise((resolve, reject) => requests.push({resolve, reject})), () => {}, 10);
const tick = () => new Promise(resolve => setTimeout(resolve, 30));
player.play(); player.play(); void player.step();
assert.equal(requests.length, 1);
player.pause(); requests[0].resolve(); await tick();
assert.equal(requests.length, 1);
assert.equal(player.pending, false);
player.play(); assert.equal(requests.length, 2);
requests[1].resolve(); await tick(); assert.equal(requests.length, 3);
assert.equal(player.pending, true);
player.reset(); player.play(); assert.equal(requests.length, 4);
requests[2].resolve(); await tick();
assert.equal(player.pending, true); assert.equal(requests.length, 4);
player.pause(); requests[3].resolve(); await tick();
assert.equal(player.pending, false); assert.equal(requests.length, 4);
void player.step(); assert.equal(requests.length, 5);
requests[4].reject(new Error("worker failed")); await tick();
assert.equal(player.playing, false); assert.equal(player.pending, false);
player.reset();
console.log("automaton scheduling preserves backpressure, pause, reset generations and failure recovery");
